const skills = [
    { id: 1, name: "JavaScript" },
    { id: 2, name: "Python" },
    { id: 3, name: "Java" },
    { id: 4, name: "C#" },
    { id: 5, name: "C++" },
    { id: 6, name: "Ruby" },
    { id: 7, name: "PHP" },
    { id: 8, name: "Swift" },
    { id: 9, name: "Kotlin" },
    { id: 10, name: "Go" },
    { id: 11, name: "TypeScript" },
    { id: 12, name: "HTML" },
    { id: 13, name: "CSS" },
    { id: 14, name: "SQL" },
    { id: 15, name: "NoSQL" },
    { id: 16, name: "React" },
    { id: 17, name: "Angular" },
    { id: 18, name: "Vue.js" },
    { id: 19, name: "Node.js" },
    { id: 20, name: "Express.js" },
    { id: 21, name: "Django" },
    { id: 22, name: "Flask" },
    { id: 23, name: "Spring Boot" },
    { id: 24, name: "Ruby on Rails" },
    { id: 25, name: "ASP.NET" },
    { id: 26, name: "Laravel" },
    { id: 27, name: "Symfony" },
    { id: 28, name: "Flutter" },
    { id: 29, name: "React Native" },
    { id: 30, name: "TensorFlow" },
    { id: 31, name: "Keras" },
    { id: 32, name: "PyTorch" },
    { id: 33, name: "Scikit-learn" },
    { id: 34, name: "Pandas" },
    { id: 35, name: "NumPy" },
    { id: 36, name: "Hadoop" },
    { id: 37, name: "Spark" },
    { id: 38, name: "AWS" },
    { id: 39, name: "Azure" },
    { id: 40, name: "Google Cloud" },
    { id: 41, name: "Docker" },
    { id: 42, name: "Kubernetes" },
    { id: 43, name: "Jenkins" },
    { id: 44, name: "Terraform" },
    { id: 45, name: "Ansible" },
    { id: 46, name: "Git" },
    { id: 47, name: "GitHub" },
    { id: 48, name: "GitLab" },
    { id: 49, name: "Jira" },
    { id: 50, name: "Confluence" },
    { id: 51, name: "Agile Methodologies" },
    { id: 52, name: "Scrum" },
    { id: 53, name: "DevOps" },
    { id: 54, name: "CI/CD" },
    { id: 55, name: "Linux" },
    { id: 56, name: "Unix" },
    { id: 57, name: "Windows Server" },
    { id: 58, name: "iOS Development" },
    { id: 59, name: "Android Development" },
    { id: 60, name: "Machine Learning" },
    { id: 61, name: "Artificial Intelligence" },
    { id: 62, name: "Data Science" },
    { id: 63, name: "Big Data" },
    { id: 64, name: "Blockchain" },
    { id: 65, name: "Cybersecurity" },
    { id: 66, name: "Penetration Testing" },
    { id: 67, name: "Ethical Hacking" },
    { id: 68, name: "Networking" },
    { id: 69, name: "Cloud Computing" },
    { id: 70, name: "Web Development" },
    { id: 71, name: "Mobile Development" },
    { id: 72, name: "Software Testing" },
    { id: 73, name: "Quality Assurance (QA)" },
    { id: 74, name: "Test Automation" },
    { id: 75, name: "Selenium" },
    { id: 76, name: "Cucumber" },
    { id: 77, name: "Robot Framework" },
    { id: 78, name: "Apache Kafka" },
    { id: 79, name: "RabbitMQ" },
    { id: 80, name: "ElasticSearch" },
    { id: 81, name: "Redis" },
    { id: 82, name: "MongoDB" },
    { id: 83, name: "PostgreSQL" },
    { id: 84, name: "MySQL" },
    { id: 85, name: "Oracle" },
    { id: 86, name: "SQLite" },
    { id: 87, name: "GraphQL" },
    { id: 88, name: "RESTful APIs" },
    { id: 89, name: "SOAP" },
    { id: 90, name: "Microservices" },
    { id: 91, name: "Event-Driven Architecture" },
    { id: 92, name: "Serverless Architecture" },
    { id: 93, name: "UX/UI Design" },
    { id: 94, name: "Figma" },
    { id: 95, name: "Adobe XD" },
    { id: 96, name: "Sketch" },
    { id: 97, name: "Photoshop" },
    { id: 98, name: "Illustrator" },
    { id: 99, name: "InDesign" },
    { id: 100, name: "Canva" },
    { id: 101, name: "WordPress" },
    { id: 102, name: "Shopify" },
    { id: 103, name: "Magento" },
    { id: 104, name: "Salesforce" },
    { id: 105, name: "SAP" },
    { id: 106, name: "Oracle ERP" },
    { id: 107, name: "Microsoft Dynamics" },
    { id: 108, name: "Tableau" },
    { id: 109, name: "Power BI" },
    { id: 110, name: "QlikView" },
    { id: 111, name: "Data Warehousing" },
    { id: 112, name: "ETL" },
    { id: 113, name: "Business Intelligence" },
    { id: 114, name: "R" },
    { id: 115, name: "MATLAB" },
    { id: 116, name: "SAS" },
    { id: 117, name: "SPSS" },
    { id: 118, name: "Jupyter" },
    { id: 119, name: "RStudio" },
    { id: 120, name: "Apache Cassandra" },
];

export default skills;
